language: C

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang
      osx_image: xcode7.3
  allow_failures: # temporary
    - os: osx

# only works on linux
addons:
  apt:
    packages:
      - python
      - flex
      - bison
      - libcppunit-dev

# need this to install dependencies on osx
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew update ; brew install python flex bison cppunit; fi

# TODO add --affine when tests are fixed
install: 
  - ./waf configure --prefix=$HOME --with-optim --optim-lib=soplex
  - ./waf build install clean

# command to run tests
# TODO: add nonreg tests
script:  
  - ./waf utest
#  - __build__/examples/optimizer04 benchs/benchs-optim/coconutbenchmark-library1/ex8_5_2.bch acidhc4 compo smearsumrel 1.e-8 1.e-8 100 1

after_failure:
  - cat __build__/*.log
