language: python
python:
  - "2.7"
#
virtualenv:
  system_site_packages: true
# 
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y --force-yes python2.7 flex bison gcc g++ coinor-clp coinor-libclp-dev 
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: ./waf configure && ./waf 
# command to run tests, e.g. python setup.py test
script:  __build__/examples/optimizer04 benchs/benchs-optim/coconutbenchmark-library1/ex2_1_9.bch acidhc4 compo smearsumrel 1.e-8 1.e-8 10 1
