language: python
python:
  - "2.7"
# 
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y --force-yes python2.7 flex bison gcc g++ libcppunit-dev pkg-config coinor-libclp-dev 
# command to install dependencies
install: 
  - cd plugins/optim/; tar xvf soplex-1.7.1.tar && cd soplex-1.7.1 && make install && cd ../../..
  - ./waf configure --with-optim --with-soplex=$PWD/plugins/optim/soplex-1.7.1 --with-affine-extended --with-debug 
  - sudo ./waf install
  - export PKG_CONFIG_PATH=/usr/local/share/pkgconfig/
#  - cd tests/ && make utest && cd ..
  - cd tests/ && make utest && cd ..
  - cd plugins/optim/tests/ && make nonreg && cd ../../..
  - cd plugins/affine/tests/ && make utest DEBUG=yes && cd ../../..

# command to run tests
script:  
#  - __build__/examples/optimizer04 benchs/benchs-optim/coconutbenchmark-library1/ex8_5_2.bch acidhc4 compo smearsumrel 1.e-8 1.e-8 100 1
  - cd tests/ && ./utest && cd ..
#  - cd plugins/optim/tests/ && ./nonreg nonreg-travis-soplex-filib.res && cd ../../..
  - cd plugins/affine/tests/ && ./utest && cd ..

