version: build{build}
#os: Visual Studio 2015
#clone_folder: C:\projects\ibex-lib
#test: off
#configuration:
#    - Release
#    # - Debug
environment:
  matrix:
    - name: win32
      platform: mingw
    - name: win64
      platform: mingw-w64

install:
  - echo Running install

build_script:
  - echo Running build
